#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Camera_SpectateHUD

#include "Basic.hpp"

#include "Camera_SpectateHUD_classes.hpp"
#include "Camera_SpectateHUD_parameters.hpp"


namespace SDK
{

// Function Camera_SpectateHUD.Camera_SpectateHUD_C.Tracking User
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UCamera_SpectateHUD_C::Tracking_User()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "Tracking User");

	Params::Camera_SpectateHUD_C_Tracking_User Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Camera_SpectateHUD.Camera_SpectateHUD_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCamera_SpectateHUD_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "Tick");

	Params::Camera_SpectateHUD_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Camera_SpectateHUD.Camera_SpectateHUD_C.Hud Visibility Camera Lag
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UCamera_SpectateHUD_C::Hud_Visibility_Camera_Lag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "Hud Visibility Camera Lag");

	Params::Camera_SpectateHUD_C_Hud_Visibility_Camera_Lag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Camera_SpectateHUD.Camera_SpectateHUD_C.Hud Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UCamera_SpectateHUD_C::Hud_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "Hud Visibility");

	Params::Camera_SpectateHUD_C_Hud_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Camera_SpectateHUD.Camera_SpectateHUD_C.FOV Amount
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UCamera_SpectateHUD_C::FOV_Amount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "FOV Amount");

	Params::Camera_SpectateHUD_C_FOV_Amount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Camera_SpectateHUD.Camera_SpectateHUD_C.ExecuteUbergraph_Camera_SpectateHUD
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCamera_SpectateHUD_C::ExecuteUbergraph_Camera_SpectateHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Camera_SpectateHUD_C", "ExecuteUbergraph_Camera_SpectateHUD");

	Params::Camera_SpectateHUD_C_ExecuteUbergraph_Camera_SpectateHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

