#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChatBoxWidget

#include "Basic.hpp"

#include "ChatBoxWidget_classes.hpp"
#include "ChatBoxWidget_parameters.hpp"


namespace SDK
{

// Function ChatBoxWidget.ChatBoxWidget_C.Send In Text
// (BlueprintCallable, BlueprintEvent)

void UChatBoxWidget_C::Send_In_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "Send In Text");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ChatBoxWidget.ChatBoxWidget_C.OnPreviewKeyDown
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UChatBoxWidget_C::OnPreviewKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "OnPreviewKeyDown");

	Params::ChatBoxWidget_C_OnPreviewKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ChatBoxWidget.ChatBoxWidget_C.InpActEvt_T_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UChatBoxWidget_C::InpActEvt_T_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "InpActEvt_T_K2Node_InputKeyEvent_0");

	Params::ChatBoxWidget_C_InpActEvt_T_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ChatBoxWidget.ChatBoxWidget_C.ExecuteUbergraph_ChatBoxWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChatBoxWidget_C::ExecuteUbergraph_ChatBoxWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "ExecuteUbergraph_ChatBoxWidget");

	Params::ChatBoxWidget_C_ExecuteUbergraph_ChatBoxWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ChatBoxWidget.ChatBoxWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UChatBoxWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ChatBoxWidget.ChatBoxWidget_C.Add Message Client
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FString&                    Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UChatBoxWidget_C::Add_Message_Client(class APlayerState* Player, const class FText& Text, const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChatBoxWidget_C", "Add Message Client");

	Params::ChatBoxWidget_C_Add_Message_Client Parms{};

	Parms.Player = Player;
	Parms.Text = std::move(Text);
	Parms.Name_0 = std::move(Name_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

