#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameStateBP

#include "Basic.hpp"

#include "GameStateBP_classes.hpp"
#include "GameStateBP_parameters.hpp"


namespace SDK
{

// Function GameStateBP.GameStateBP_C.Vanished server
// (Net, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTransform&                SpawnTransform                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGameStateBP_C::Vanished_server(const struct FTransform& SpawnTransform, class AActor* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "Vanished server");

	Params::GameStateBP_C_Vanished_server Parms{};

	Parms.SpawnTransform = std::move(SpawnTransform);
	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameStateBP.GameStateBP_C.Updatedoer
// (BlueprintCallable, BlueprintEvent)

void AGameStateBP_C::Updatedoer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "Updatedoer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameStateBP.GameStateBP_C.Send Message Server
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Player_State                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      Message                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FString&                    Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AGameStateBP_C::Send_Message_Server(class APlayerState* Player_State, const class FText& Message, const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "Send Message Server");

	Params::GameStateBP_C_Send_Message_Server Parms{};

	Parms.Player_State = Player_State;
	Parms.Message = std::move(Message);
	Parms.Name_0 = std::move(Name_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameStateBP.GameStateBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AGameStateBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameStateBP.GameStateBP_C.On_Vanished
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTransform&                Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// class ACharacter*                       Real                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGameStateBP_C::On_Vanished(const struct FTransform& Transform, class ACharacter* Real)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "On_Vanished");

	Params::GameStateBP_C_On_Vanished Parms{};

	Parms.Transform = std::move(Transform);
	Parms.Real = Real;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameStateBP.GameStateBP_C.On_Bannana
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                NewParam1                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGameStateBP_C::On_Bannana(const struct FRotator& NewParam, class APlayerController* NewParam1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "On_Bannana");

	Params::GameStateBP_C_On_Bannana Parms{};

	Parms.NewParam = std::move(NewParam);
	Parms.NewParam1 = NewParam1;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameStateBP.GameStateBP_C.Host Start
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void AGameStateBP_C::Host_Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "Host Start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameStateBP.GameStateBP_C.Host End
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void AGameStateBP_C::Host_End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "Host End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameStateBP.GameStateBP_C.ExecuteUbergraph_GameStateBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGameStateBP_C::ExecuteUbergraph_GameStateBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameStateBP_C", "ExecuteUbergraph_GameStateBP");

	Params::GameStateBP_C_ExecuteUbergraph_GameStateBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

