#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GraphicsMenu

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GraphicsMenu.GraphicsMenu_C.Save game
// 0x0060 (0x0060 - 0x0000)
struct GraphicsMenu_C_Save_game final
{
public:
	bool                                          Lumin;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Field_Of_Vision;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MouseSens;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Kill_Confirmed_Widget_0;                           // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Hitmarker_Size_0;                                  // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Hitmarker_Type_0;                                  // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USaveOptions_C*                         K2Node_DynamicCast_AsSave_Options;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveGameToSlot_ReturnValue;               // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USaveOptions_C*                         CallFunc_CreateSaveGameObject_ReturnValue;         // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_Save_game) == 0x000008, "Wrong alignment on GraphicsMenu_C_Save_game");
static_assert(sizeof(GraphicsMenu_C_Save_game) == 0x000060, "Wrong size on GraphicsMenu_C_Save_game");
static_assert(offsetof(GraphicsMenu_C_Save_game, Lumin) == 0x000000, "Member 'GraphicsMenu_C_Save_game::Lumin' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, Field_Of_Vision) == 0x000008, "Member 'GraphicsMenu_C_Save_game::Field_Of_Vision' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, MouseSens) == 0x000010, "Member 'GraphicsMenu_C_Save_game::MouseSens' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, Kill_Confirmed_Widget_0) == 0x000018, "Member 'GraphicsMenu_C_Save_game::Kill_Confirmed_Widget_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, Hitmarker_Size_0) == 0x000020, "Member 'GraphicsMenu_C_Save_game::Hitmarker_Size_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, Hitmarker_Type_0) == 0x000030, "Member 'GraphicsMenu_C_Save_game::Hitmarker_Type_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, ReturnValue) == 0x000040, "Member 'GraphicsMenu_C_Save_game::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, K2Node_DynamicCast_AsSave_Options) == 0x000048, "Member 'GraphicsMenu_C_Save_game::K2Node_DynamicCast_AsSave_Options' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'GraphicsMenu_C_Save_game::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, CallFunc_SaveGameToSlot_ReturnValue) == 0x000051, "Member 'GraphicsMenu_C_Save_game::CallFunc_SaveGameToSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Save_game, CallFunc_CreateSaveGameObject_ReturnValue) == 0x000058, "Member 'GraphicsMenu_C_Save_game::CallFunc_CreateSaveGameObject_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.Load game
// 0x0068 (0x0068 - 0x0000)
struct GraphicsMenu_C_Load_game final
{
public:
	bool                                          Lumen;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Field_Of_Vision;                                   // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Kill_Confirmed_Widget_0;                           // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MouseSens;                                         // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Hitmarker_Size_0;                                  // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Hitmarker_Type_0;                                  // 0x0030(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	double                                        Snipersens;                                        // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveOptions_C*                         K2Node_DynamicCast_AsSave_Options;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USaveGame*                              CallFunc_LoadGameFromSlot_ReturnValue;             // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesSaveGameExist_ReturnValue;            // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_Load_game) == 0x000008, "Wrong alignment on GraphicsMenu_C_Load_game");
static_assert(sizeof(GraphicsMenu_C_Load_game) == 0x000068, "Wrong size on GraphicsMenu_C_Load_game");
static_assert(offsetof(GraphicsMenu_C_Load_game, Lumen) == 0x000000, "Member 'GraphicsMenu_C_Load_game::Lumen' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, Field_Of_Vision) == 0x000008, "Member 'GraphicsMenu_C_Load_game::Field_Of_Vision' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, Kill_Confirmed_Widget_0) == 0x000010, "Member 'GraphicsMenu_C_Load_game::Kill_Confirmed_Widget_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, MouseSens) == 0x000018, "Member 'GraphicsMenu_C_Load_game::MouseSens' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, Hitmarker_Size_0) == 0x000020, "Member 'GraphicsMenu_C_Load_game::Hitmarker_Size_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, Hitmarker_Type_0) == 0x000030, "Member 'GraphicsMenu_C_Load_game::Hitmarker_Type_0' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, Snipersens) == 0x000040, "Member 'GraphicsMenu_C_Load_game::Snipersens' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, K2Node_DynamicCast_AsSave_Options) == 0x000048, "Member 'GraphicsMenu_C_Load_game::K2Node_DynamicCast_AsSave_Options' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'GraphicsMenu_C_Load_game::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, CallFunc_LoadGameFromSlot_ReturnValue) == 0x000058, "Member 'GraphicsMenu_C_Load_game::CallFunc_LoadGameFromSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Load_game, CallFunc_DoesSaveGameExist_ReturnValue) == 0x000060, "Member 'GraphicsMenu_C_Load_game::CallFunc_DoesSaveGameExist_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetWindowMode
// 0x0040 (0x0040 - 0x0000)
struct GraphicsMenu_C_GetWindowMode final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0018)()
};
static_assert(alignof(GraphicsMenu_C_GetWindowMode) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetWindowMode");
static_assert(sizeof(GraphicsMenu_C_GetWindowMode) == 0x000040, "Wrong size on GraphicsMenu_C_GetWindowMode");
static_assert(offsetof(GraphicsMenu_C_GetWindowMode, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetWindowMode::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetWindowMode, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000018, "Member 'GraphicsMenu_C_GetWindowMode::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetWindowMode, CallFunc_Conv_StringToText_ReturnValue) == 0x000028, "Member 'GraphicsMenu_C_GetWindowMode::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetVsync
// 0x0018 (0x0018 - 0x0000)
struct GraphicsMenu_C_GetVsync final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(GraphicsMenu_C_GetVsync) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetVsync");
static_assert(sizeof(GraphicsMenu_C_GetVsync) == 0x000018, "Wrong size on GraphicsMenu_C_GetVsync");
static_assert(offsetof(GraphicsMenu_C_GetVsync, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetVsync::ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetTexture
// 0x0020 (0x0020 - 0x0000)
struct GraphicsMenu_C_GetTexture final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_GetTexture) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetTexture");
static_assert(sizeof(GraphicsMenu_C_GetTexture) == 0x000020, "Wrong size on GraphicsMenu_C_GetTexture");
static_assert(offsetof(GraphicsMenu_C_GetTexture, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetTexture::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetTexture, K2Node_SwitchInteger_CmpSuccess) == 0x000018, "Member 'GraphicsMenu_C_GetTexture::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetText_3
// 0x0030 (0x0030 - 0x0000)
struct GraphicsMenu_C_GetText_3 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0018(0x0018)()
};
static_assert(alignof(GraphicsMenu_C_GetText_3) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetText_3");
static_assert(sizeof(GraphicsMenu_C_GetText_3) == 0x000030, "Wrong size on GraphicsMenu_C_GetText_3");
static_assert(offsetof(GraphicsMenu_C_GetText_3, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetText_3::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_3, CallFunc_Conv_FloatToText_ReturnValue) == 0x000018, "Member 'GraphicsMenu_C_GetText_3::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetText_2
// 0x0090 (0x0090 - 0x0000)
struct GraphicsMenu_C_GetText_2 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0068(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0018)()
};
static_assert(alignof(GraphicsMenu_C_GetText_2) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetText_2");
static_assert(sizeof(GraphicsMenu_C_GetText_2) == 0x000090, "Wrong size on GraphicsMenu_C_GetText_2");
static_assert(offsetof(GraphicsMenu_C_GetText_2, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetText_2::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_2, K2Node_MakeStruct_FormatArgumentData) == 0x000018, "Member 'GraphicsMenu_C_GetText_2::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_2, K2Node_MakeArray_Array) == 0x000068, "Member 'GraphicsMenu_C_GetText_2::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_2, CallFunc_Format_ReturnValue) == 0x000078, "Member 'GraphicsMenu_C_GetText_2::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetText_1
// 0x0090 (0x0090 - 0x0000)
struct GraphicsMenu_C_GetText_1 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0068(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0018)()
};
static_assert(alignof(GraphicsMenu_C_GetText_1) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetText_1");
static_assert(sizeof(GraphicsMenu_C_GetText_1) == 0x000090, "Wrong size on GraphicsMenu_C_GetText_1");
static_assert(offsetof(GraphicsMenu_C_GetText_1, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetText_1::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_1, K2Node_MakeStruct_FormatArgumentData) == 0x000018, "Member 'GraphicsMenu_C_GetText_1::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_1, K2Node_MakeArray_Array) == 0x000068, "Member 'GraphicsMenu_C_GetText_1::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_1, CallFunc_Format_ReturnValue) == 0x000078, "Member 'GraphicsMenu_C_GetText_1::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetText_0
// 0x00A0 (0x00A0 - 0x0000)
struct GraphicsMenu_C_GetText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	int64                                         CallFunc_Round64_ReturnValue;                      // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0020(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0070(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0080(0x0018)()
	double                                        CallFunc_Round64_A_WideningCast;                   // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_GetText_0) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetText_0");
static_assert(sizeof(GraphicsMenu_C_GetText_0) == 0x0000A0, "Wrong size on GraphicsMenu_C_GetText_0");
static_assert(offsetof(GraphicsMenu_C_GetText_0, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_0, CallFunc_Round64_ReturnValue) == 0x000018, "Member 'GraphicsMenu_C_GetText_0::CallFunc_Round64_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_0, K2Node_MakeStruct_FormatArgumentData) == 0x000020, "Member 'GraphicsMenu_C_GetText_0::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_0, K2Node_MakeArray_Array) == 0x000070, "Member 'GraphicsMenu_C_GetText_0::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_0, CallFunc_Format_ReturnValue) == 0x000080, "Member 'GraphicsMenu_C_GetText_0::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetText_0, CallFunc_Round64_A_WideningCast) == 0x000098, "Member 'GraphicsMenu_C_GetText_0::CallFunc_Round64_A_WideningCast' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetResolution
// 0x0070 (0x0070 - 0x0000)
struct GraphicsMenu_C_GetResolution final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_1;           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0058(0x0018)()
};
static_assert(alignof(GraphicsMenu_C_GetResolution) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetResolution");
static_assert(sizeof(GraphicsMenu_C_GetResolution) == 0x000070, "Wrong size on GraphicsMenu_C_GetResolution");
static_assert(offsetof(GraphicsMenu_C_GetResolution, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetResolution::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetResolution, CallFunc_Conv_IntToString_ReturnValue) == 0x000018, "Member 'GraphicsMenu_C_GetResolution::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetResolution, CallFunc_Conv_IntToString_ReturnValue_1) == 0x000028, "Member 'GraphicsMenu_C_GetResolution::CallFunc_Conv_IntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetResolution, CallFunc_Concat_StrStr_ReturnValue) == 0x000038, "Member 'GraphicsMenu_C_GetResolution::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetResolution, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000048, "Member 'GraphicsMenu_C_GetResolution::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetResolution, CallFunc_Conv_StringToText_ReturnValue) == 0x000058, "Member 'GraphicsMenu_C_GetResolution::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetFoliage
// 0x0020 (0x0020 - 0x0000)
struct GraphicsMenu_C_GetFoliage final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_GetFoliage) == 0x000008, "Wrong alignment on GraphicsMenu_C_GetFoliage");
static_assert(sizeof(GraphicsMenu_C_GetFoliage) == 0x000020, "Wrong size on GraphicsMenu_C_GetFoliage");
static_assert(offsetof(GraphicsMenu_C_GetFoliage, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetFoliage::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_GetFoliage, K2Node_SwitchInteger_CmpSuccess) == 0x000018, "Member 'GraphicsMenu_C_GetFoliage::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.GetCheckedState_0
// 0x0001 (0x0001 - 0x0000)
struct GraphicsMenu_C_GetCheckedState_0 final
{
public:
	ECheckBoxState                                ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_GetCheckedState_0) == 0x000001, "Wrong alignment on GraphicsMenu_C_GetCheckedState_0");
static_assert(sizeof(GraphicsMenu_C_GetCheckedState_0) == 0x000001, "Wrong size on GraphicsMenu_C_GetCheckedState_0");
static_assert(offsetof(GraphicsMenu_C_GetCheckedState_0, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_GetCheckedState_0::ReturnValue' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.Get_Shadow
// 0x0020 (0x0020 - 0x0000)
struct GraphicsMenu_C_Get_Shadow final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_Get_Shadow) == 0x000008, "Wrong alignment on GraphicsMenu_C_Get_Shadow");
static_assert(sizeof(GraphicsMenu_C_Get_Shadow) == 0x000020, "Wrong size on GraphicsMenu_C_Get_Shadow");
static_assert(offsetof(GraphicsMenu_C_Get_Shadow, ReturnValue) == 0x000000, "Member 'GraphicsMenu_C_Get_Shadow::ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_Get_Shadow, K2Node_SwitchInteger_CmpSuccess) == 0x000018, "Member 'GraphicsMenu_C_Get_Shadow::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.ExecuteUbergraph_GraphicsMenu
// 0x0190 (0x0190 - 0x0000)
struct GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint;                        // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint_1;                      // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint_2;                      // 0x0014(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint_3;                      // 0x001C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint_4;                      // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_2;          // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_3;          // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_4;          // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              K2Node_MakeStruct_IntPoint_5;                      // 0x0044(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_1;                     // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_1;                      // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Clamp_ReturnValue_2;                      // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue_1;             // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue_1;              // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9E[0x2];                                       // 0x009E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_3;                      // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_4;                      // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_5;                      // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_2;            // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_3;            // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_6;                      // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_7;                      // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Clamp_ReturnValue_8;                      // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_4;            // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_9;                      // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue_1;        // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              CallFunc_GetScreenResolution_ReturnValue;          // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetTextureQuality_ReturnValue;            // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFoliageQuality_ReturnValue;            // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWindowMode                                   CallFunc_GetFullscreenMode_ReturnValue;            // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FD[0x3];                                       // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetFrameRateLimit_ReturnValue;            // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVSyncEnabled_ReturnValue;               // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x0105(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_106[0x2];                                      // 0x0106(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATrainGusPlayer_C*                      K2Node_DynamicCast_AsTrain_Gus_Player;             // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Load_Game_Lumen;                          // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11A[0x6];                                      // 0x011A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Load_game_Field_Of_Vision;                // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Load_game_Kill_Confirmed_Widget;          // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Load_Game_MouseSens;                      // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Load_game_Hitmarker_Size;                 // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Load_game_Hitmarker_Type;                 // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	double                                        CallFunc_Load_Game_Snipersens;                     // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Save_Game_ReturnValue;                    // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_A_WideningCast;     // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_WideningCast;          // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Frame_Limit_NarrowingCast;      // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Frame_Limit_NarrowingCast_1;    // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Sens_NarrowingCast;             // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Save_Game_MouseSens_WideningCast;         // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu) == 0x000008, "Wrong alignment on GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu");
static_assert(sizeof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu) == 0x000190, "Wrong size on GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, EntryPoint) == 0x000000, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint) == 0x000004, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint_1) == 0x00000C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint_2) == 0x000014, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint_2' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint_3) == 0x00001C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint_3' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint_4) == 0x000024, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint_4' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00002C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Conv_BoolToString_ReturnValue) == 0x000030, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Conv_BoolToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x000040, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_EqualEqual_IntInt_ReturnValue_2) == 0x000041, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_EqualEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_EqualEqual_IntInt_ReturnValue_3) == 0x000042, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_EqualEqual_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_EqualEqual_IntInt_ReturnValue_4) == 0x000043, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_EqualEqual_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_MakeStruct_IntPoint_5) == 0x000044, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_MakeStruct_IntPoint_5' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetGameUserSettings_ReturnValue) == 0x000050, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000058, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000060, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_FClamp_ReturnValue) == 0x000068, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_FClamp_ReturnValue_1) == 0x000070, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_FClamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000078, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_IntInt_ReturnValue) == 0x00007C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_IntInt_ReturnValue_1) == 0x000080, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue) == 0x000084, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_1) == 0x000088, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Conv_IntToByte_ReturnValue) == 0x00008C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_IntInt_ReturnValue) == 0x000090, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetValidValue_ReturnValue) == 0x000094, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetValidValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_2) == 0x000098, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Conv_IntToByte_ReturnValue_1) == 0x00009C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Conv_IntToByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetValidValue_ReturnValue_1) == 0x00009D, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetValidValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x0000A0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_3) == 0x0000A4, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000A8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000AC, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_4) == 0x0000B0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_5) == 0x0000B4, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_IntInt_ReturnValue_2) == 0x0000B8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_IntInt_ReturnValue_3) == 0x0000BC, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_6) == 0x0000C0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_7) == 0x0000C4, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_IntInt_ReturnValue_4) == 0x0000C8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_SwitchInteger_CmpSuccess) == 0x0000CC, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_8) == 0x0000D0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_IntInt_ReturnValue_4) == 0x0000D4, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Clamp_ReturnValue_9) == 0x0000D8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Clamp_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetGameUserSettings_ReturnValue_1) == 0x0000E0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetGameUserSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetScreenResolution_ReturnValue) == 0x0000E8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetScreenResolution_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetTextureQuality_ReturnValue) == 0x0000F0, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetTextureQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetShadowQuality_ReturnValue) == 0x0000F4, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetShadowQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetFoliageQuality_ReturnValue) == 0x0000F8, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetFoliageQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetFullscreenMode_ReturnValue) == 0x0000FC, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetFullscreenMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetFrameRateLimit_ReturnValue) == 0x000100, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetFrameRateLimit_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_IsVSyncEnabled_ReturnValue) == 0x000104, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_IsVSyncEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_ComponentBoundEvent_bIsChecked) == 0x000105, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_ComponentBoundEvent_bIsChecked' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_GetPlayerPawn_ReturnValue) == 0x000108, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_DynamicCast_AsTrain_Gus_Player) == 0x000110, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_DynamicCast_AsTrain_Gus_Player' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_DynamicCast_bSuccess) == 0x000118, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_Game_Lumen) == 0x000119, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_Game_Lumen' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_game_Field_Of_Vision) == 0x000120, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_game_Field_Of_Vision' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_game_Kill_Confirmed_Widget) == 0x000128, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_game_Kill_Confirmed_Widget' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_Game_MouseSens) == 0x000130, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_Game_MouseSens' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_game_Hitmarker_Size) == 0x000138, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_game_Hitmarker_Size' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_game_Hitmarker_Type) == 0x000148, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_game_Hitmarker_Type' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Load_Game_Snipersens) == 0x000158, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Load_Game_Snipersens' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Save_Game_ReturnValue) == 0x000160, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Save_Game_ReturnValue' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Subtract_DoubleDouble_A_WideningCast) == 0x000168, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Subtract_DoubleDouble_A_WideningCast' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Add_DoubleDouble_A_WideningCast) == 0x000170, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Add_DoubleDouble_A_WideningCast' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_VariableSet_Frame_Limit_NarrowingCast) == 0x000178, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_VariableSet_Frame_Limit_NarrowingCast' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_VariableSet_Frame_Limit_NarrowingCast_1) == 0x00017C, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_VariableSet_Frame_Limit_NarrowingCast_1' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, K2Node_VariableSet_Sens_NarrowingCast) == 0x000180, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::K2Node_VariableSet_Sens_NarrowingCast' has a wrong offset!");
static_assert(offsetof(GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu, CallFunc_Save_Game_MouseSens_WideningCast) == 0x000188, "Member 'GraphicsMenu_C_ExecuteUbergraph_GraphicsMenu::CallFunc_Save_Game_MouseSens_WideningCast' has a wrong offset!");

// Function GraphicsMenu.GraphicsMenu_C.BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'GraphicsMenu_C_BndEvt__GraphicsMenu_CheckBox_0_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

}

