#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GremlinAIController

#include "Basic.hpp"


namespace SDK::Params
{

// Function GremlinAIController.GremlinAIController_C.ExecuteUbergraph_GremlinAIController
// 0x0008 (0x0008 - 0x0000)
struct GremlinAIController_C_ExecuteUbergraph_GremlinAIController final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RunBehaviorTree_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GremlinAIController_C_ExecuteUbergraph_GremlinAIController) == 0x000004, "Wrong alignment on GremlinAIController_C_ExecuteUbergraph_GremlinAIController");
static_assert(sizeof(GremlinAIController_C_ExecuteUbergraph_GremlinAIController) == 0x000008, "Wrong size on GremlinAIController_C_ExecuteUbergraph_GremlinAIController");
static_assert(offsetof(GremlinAIController_C_ExecuteUbergraph_GremlinAIController, EntryPoint) == 0x000000, "Member 'GremlinAIController_C_ExecuteUbergraph_GremlinAIController::EntryPoint' has a wrong offset!");
static_assert(offsetof(GremlinAIController_C_ExecuteUbergraph_GremlinAIController, CallFunc_RunBehaviorTree_ReturnValue) == 0x000004, "Member 'GremlinAIController_C_ExecuteUbergraph_GremlinAIController::CallFunc_RunBehaviorTree_ReturnValue' has a wrong offset!");

}

