#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GremlinAIController

#include "Basic.hpp"

#include "GremlinAIController_classes.hpp"
#include "GremlinAIController_parameters.hpp"


namespace SDK
{

// Function GremlinAIController.GremlinAIController_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AGremlinAIController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GremlinAIController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GremlinAIController.GremlinAIController_C.ExecuteUbergraph_GremlinAIController
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGremlinAIController_C::ExecuteUbergraph_GremlinAIController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GremlinAIController_C", "ExecuteUbergraph_GremlinAIController");

	Params::GremlinAIController_C_ExecuteUbergraph_GremlinAIController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

