#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GusAnimBpNewer

#include "Basic.hpp"

#include "GusAnimBpNewer_classes.hpp"
#include "GusAnimBpNewer_parameters.hpp"


namespace SDK
{

// Function GusAnimBpNewer.GusAnimBpNewer_C.OnNewFunction_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UGusAnimBpNewer_C::OnNewFunction_0(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "OnNewFunction_0");

	Params::GusAnimBpNewer_C_OnNewFunction_0 Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.Footsteps Multicast
// (BlueprintCallable, BlueprintEvent)

void UGusAnimBpNewer_C::Footsteps_Multicast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "Footsteps Multicast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.Footstep Sound Server
// (Net, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPhysicalSurface                        Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGusAnimBpNewer_C::Footstep_Sound_Server(EPhysicalSurface Selection, const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "Footstep Sound Server");

	Params::GusAnimBpNewer_C_Footstep_Sound_Server Parms{};

	Parms.Selection = Selection;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.Footstep Sound Multicast
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPhysicalSurface                        Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGusAnimBpNewer_C::Footstep_Sound_Multicast(EPhysicalSurface Selection, const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "Footstep Sound Multicast");

	Params::GusAnimBpNewer_C_Footstep_Sound_Multicast Parms{};

	Parms.Selection = Selection;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.ExecuteUbergraph_GusAnimBpNewer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGusAnimBpNewer_C::ExecuteUbergraph_GusAnimBpNewer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "ExecuteUbergraph_GusAnimBpNewer");

	Params::GusAnimBpNewer_C_ExecuteUbergraph_GusAnimBpNewer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_504CB1DA4042BE61DCAA15856D4C2485
// (BlueprintEvent)

void UGusAnimBpNewer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_504CB1DA4042BE61DCAA15856D4C2485()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_504CB1DA4042BE61DCAA15856D4C2485");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_1481D35B41056CDB56881690B69F23D3
// (BlueprintEvent)

void UGusAnimBpNewer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_1481D35B41056CDB56881690B69F23D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GusAnimBpNewer_AnimGraphNode_TransitionResult_1481D35B41056CDB56881690B69F23D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.BodyPitchServer
// (Net, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Body_Pitch_X__Roll_                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGusAnimBpNewer_C::BodyPitchServer(float Body_Pitch_X__Roll_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "BodyPitchServer");

	Params::GusAnimBpNewer_C_BodyPitchServer Parms{};

	Parms.Body_Pitch_X__Roll_ = Body_Pitch_X__Roll_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGusAnimBpNewer_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "BlueprintUpdateAnimation");

	Params::GusAnimBpNewer_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UGusAnimBpNewer_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.AnimNotify_Footstep
// (BlueprintCallable, BlueprintEvent)

void UGusAnimBpNewer_C::AnimNotify_Footstep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "AnimNotify_Footstep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GusAnimBpNewer.GusAnimBpNewer_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UGusAnimBpNewer_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GusAnimBpNewer_C", "AnimGraph");

	Params::GusAnimBpNewer_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

