#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KickWidget

#include "Basic.hpp"

#include "KickWidget_classes.hpp"
#include "KickWidget_parameters.hpp"


namespace SDK
{

// Function KickWidget.KickWidget_C.InpActEvt_F2_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UKickWidget_C::InpActEvt_F2_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "InpActEvt_F2_K2Node_InputKeyEvent_0");

	Params::KickWidget_C_InpActEvt_F2_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function KickWidget.KickWidget_C.InpActEvt_F1_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UKickWidget_C::InpActEvt_F1_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "InpActEvt_F1_K2Node_InputKeyEvent_1");

	Params::KickWidget_C_InpActEvt_F1_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function KickWidget.KickWidget_C.Get_TextVoteYes_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UKickWidget_C::Get_TextVoteYes_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "Get_TextVoteYes_Text_0");

	Params::KickWidget_C_Get_TextVoteYes_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function KickWidget.KickWidget_C.Get_TextVoteNo_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UKickWidget_C::Get_TextVoteNo_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "Get_TextVoteNo_Text_0");

	Params::KickWidget_C_Get_TextVoteNo_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function KickWidget.KickWidget_C.ExecuteUbergraph_KickWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKickWidget_C::ExecuteUbergraph_KickWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "ExecuteUbergraph_KickWidget");

	Params::KickWidget_C_ExecuteUbergraph_KickWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KickWidget.KickWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UKickWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

