#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KickWidget_Initiate

#include "Basic.hpp"

#include "KickWidget_Initiate_classes.hpp"
#include "KickWidget_Initiate_parameters.hpp"


namespace SDK
{

// Function KickWidget_Initiate.KickWidget_Initiate_C.ExecuteUbergraph_KickWidget_Initiate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKickWidget_Initiate_C::ExecuteUbergraph_KickWidget_Initiate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_Initiate_C", "ExecuteUbergraph_KickWidget_Initiate");

	Params::KickWidget_Initiate_C_ExecuteUbergraph_KickWidget_Initiate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KickWidget_Initiate.KickWidget_Initiate_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UKickWidget_Initiate_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_Initiate_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KickWidget_Initiate.KickWidget_Initiate_C.BndEvt__KickWidget_Initiate_ReasonComboBox_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKickWidget_Initiate_C::BndEvt__KickWidget_Initiate_ReasonComboBox_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_Initiate_C", "BndEvt__KickWidget_Initiate_ReasonComboBox_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature");

	Params::KickWidget_Initiate_C_BndEvt__KickWidget_Initiate_ReasonComboBox_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KickWidget_Initiate.KickWidget_Initiate_C.BndEvt__KickWidget_Initiate_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UKickWidget_Initiate_C::BndEvt__KickWidget_Initiate_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_Initiate_C", "BndEvt__KickWidget_Initiate_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KickWidget_Initiate.KickWidget_Initiate_C.BndEvt__KickWidget_Initiate_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UKickWidget_Initiate_C::BndEvt__KickWidget_Initiate_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KickWidget_Initiate_C", "BndEvt__KickWidget_Initiate_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

