#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Reticle

#include "Basic.hpp"

#include "Reticle_classes.hpp"
#include "Reticle_parameters.hpp"


namespace SDK
{

// Function Reticle.Reticle_C.ExecuteUbergraph_Reticle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReticle_C::ExecuteUbergraph_Reticle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Reticle_C", "ExecuteUbergraph_Reticle");

	Params::Reticle_C_ExecuteUbergraph_Reticle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Reticle.Reticle_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UReticle_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Reticle_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

