#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Spectate_BP

#include "Basic.hpp"

#include "Spectate_BP_classes.hpp"
#include "Spectate_BP_parameters.hpp"


namespace SDK
{

// Function Spectate_BP.Spectate_BP_C.Window doer
// (BlueprintCallable, BlueprintEvent)

void ASpectate_BP_C::Window_doer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "Window doer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectate_BP.Spectate_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASpectate_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectate_BP.Spectate_BP_C.PosterboardLerp__UpdateFunc
// (BlueprintEvent)

void ASpectate_BP_C::PosterboardLerp__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "PosterboardLerp__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectate_BP.Spectate_BP_C.PosterboardLerp__FinishedFunc
// (BlueprintEvent)

void ASpectate_BP_C::PosterboardLerp__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "PosterboardLerp__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectate_BP.Spectate_BP_C.Load Settings
// (BlueprintCallable, BlueprintEvent)

void ASpectate_BP_C::Load_Settings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "Load Settings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectate_BP.Spectate_BP_C.InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ASpectate_BP_C::InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0");

	Params::Spectate_BP_C_InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Spectate_BP.Spectate_BP_C.InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ASpectate_BP_C::InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1");

	Params::Spectate_BP_C_InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Spectate_BP.Spectate_BP_C.ExecuteUbergraph_Spectate_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASpectate_BP_C::ExecuteUbergraph_Spectate_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "ExecuteUbergraph_Spectate_BP");

	Params::Spectate_BP_C_ExecuteUbergraph_Spectate_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Spectate_BP.Spectate_BP_C.Event_Posterboard
// (BlueprintCallable, BlueprintEvent)

void ASpectate_BP_C::Event_Posterboard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectate_BP_C", "Event_Posterboard");

	UObject::ProcessEvent(Func, nullptr);
}

}

