#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TDM_UI

#include "Basic.hpp"

#include "TDM_UI_classes.hpp"
#include "TDM_UI_parameters.hpp"


namespace SDK
{

// Function TDM_UI.TDM_UI_C.Update Score
// (BlueprintCallable, BlueprintEvent)

void UTDM_UI_C::Update_Score()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Update Score");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TDM_UI.TDM_UI_C.Set Text Red Score
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UTDM_UI_C::Set_Text_Red_Score()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Set Text Red Score");

	Params::TDM_UI_C_Set_Text_Red_Score Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TDM_UI.TDM_UI_C.Set Text Blue Score
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UTDM_UI_C::Set_Text_Blue_Score()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Set Text Blue Score");

	Params::TDM_UI_C_Set_Text_Blue_Score Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TDM_UI.TDM_UI_C.Red Progress Bar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UTDM_UI_C::Red_Progress_Bar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Red Progress Bar");

	Params::TDM_UI_C_Red_Progress_Bar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TDM_UI.TDM_UI_C.Get_SkullImage_Brush_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UTDM_UI_C::Get_SkullImage_Brush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Get_SkullImage_Brush_0");

	Params::TDM_UI_C_Get_SkullImage_Brush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TDM_UI.TDM_UI_C.ExecuteUbergraph_TDM_UI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTDM_UI_C::ExecuteUbergraph_TDM_UI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "ExecuteUbergraph_TDM_UI");

	Params::TDM_UI_C_ExecuteUbergraph_TDM_UI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TDM_UI.TDM_UI_C.Blue Progress Bar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UTDM_UI_C::Blue_Progress_Bar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TDM_UI_C", "Blue Progress Bar");

	Params::TDM_UI_C_Blue_Progress_Bar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

