#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_KillFeedWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Slate_structs.hpp"
#include "BP_WidgetAligmentStruct_structs.hpp"


namespace SDK::Params
{

// Function UI_KillFeedWidget.UI_KillFeedWidget_C.Tick
// 0x0048 (0x0048 - 0x0000)
struct UI_KillFeedWidget_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_KillFeedWidget_C_Tick) == 0x000008, "Wrong alignment on UI_KillFeedWidget_C_Tick");
static_assert(sizeof(UI_KillFeedWidget_C_Tick) == 0x000048, "Wrong size on UI_KillFeedWidget_C_Tick");
static_assert(offsetof(UI_KillFeedWidget_C_Tick, MyGeometry) == 0x000000, "Member 'UI_KillFeedWidget_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_Tick, InDeltaTime) == 0x000040, "Member 'UI_KillFeedWidget_C_Tick::InDeltaTime' has a wrong offset!");

// Function UI_KillFeedWidget.UI_KillFeedWidget_C.ShowKill
// 0x0078 (0x0078 - 0x0000)
struct UI_KillFeedWidget_C_ShowKill final
{
public:
	class FText                                   KillerName;                                        // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   VictimName;                                        // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UTexture2D*                             Icon;                                              // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            KillerNameColor;                                   // 0x0038(0x0014)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FSlateColor                            VictimNameColor;                                   // 0x004C(0x0014)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FSlateColor                            IconColor;                                         // 0x0060(0x0014)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(UI_KillFeedWidget_C_ShowKill) == 0x000008, "Wrong alignment on UI_KillFeedWidget_C_ShowKill");
static_assert(sizeof(UI_KillFeedWidget_C_ShowKill) == 0x000078, "Wrong size on UI_KillFeedWidget_C_ShowKill");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, KillerName) == 0x000000, "Member 'UI_KillFeedWidget_C_ShowKill::KillerName' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, VictimName) == 0x000018, "Member 'UI_KillFeedWidget_C_ShowKill::VictimName' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, Icon) == 0x000030, "Member 'UI_KillFeedWidget_C_ShowKill::Icon' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, KillerNameColor) == 0x000038, "Member 'UI_KillFeedWidget_C_ShowKill::KillerNameColor' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, VictimNameColor) == 0x00004C, "Member 'UI_KillFeedWidget_C_ShowKill::VictimNameColor' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ShowKill, IconColor) == 0x000060, "Member 'UI_KillFeedWidget_C_ShowKill::IconColor' has a wrong offset!");

// Function UI_KillFeedWidget.UI_KillFeedWidget_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_KillFeedWidget_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_KillFeedWidget_C_PreConstruct) == 0x000001, "Wrong alignment on UI_KillFeedWidget_C_PreConstruct");
static_assert(sizeof(UI_KillFeedWidget_C_PreConstruct) == 0x000001, "Wrong size on UI_KillFeedWidget_C_PreConstruct");
static_assert(offsetof(UI_KillFeedWidget_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_KillFeedWidget_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_KillFeedWidget.UI_KillFeedWidget_C.ExecuteUbergraph_UI_KillFeedWidget
// 0x02A8 (0x02A8 - 0x0000)
struct UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_KillFeedElement_C*                  CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBP_WidgetAligmentStruct                      Temp_byte_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable;                              // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_1;                            // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBP_WidgetAligmentStruct                      Temp_byte_Variable_1;                              // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable_2;                            // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_3;                            // 0x0050(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBP_WidgetAligmentStruct                      Temp_byte_Variable_2;                              // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable_4;                            // 0x0068(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_5;                            // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBP_WidgetAligmentStruct                      Temp_byte_Variable_3;                              // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0098(0x0040)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_KillerName;                     // 0x00E0(0x0018)()
	class FText                                   K2Node_CustomEvent_VictimName;                     // 0x00F8(0x0018)()
	class UTexture2D*                             K2Node_CustomEvent_Icon;                           // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_CustomEvent_KillerNameColor;                // 0x0118(0x0014)()
	struct FSlateColor                            K2Node_CustomEvent_VictimNameColor;                // 0x012C(0x0014)()
	struct FSlateColor                            K2Node_CustomEvent_IconColor;                      // 0x0140(0x0014)()
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0160(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_KillFeedElement_C*                  K2Node_DynamicCast_AsUI_Kill_Feed_Element;         // 0x0168(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_172[0x2];                                      // 0x0172(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue;             // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue_1;                 // 0x0180(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue_1;           // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_KillFeedElement_C*                  K2Node_DynamicCast_AsUI_Kill_Feed_Element_1;       // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_GetPosition_ReturnValue;                  // 0x01B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_X;                          // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FInterpTo_Constant_ReturnValue;           // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x01E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              K2Node_Select_Default;                             // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              K2Node_Select_Default_1;                           // 0x0200(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0210(0x0020)(NoDestructor)
	struct FVector2D                              K2Node_Select_Default_2;                           // 0x0230(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue_1;           // 0x0240(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors_1;                       // 0x0248(0x0020)(NoDestructor)
	double                                        CallFunc_BreakVector2D_X_1;                        // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y_1;                        // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x0280(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              K2Node_Select_Default_3;                           // 0x0290(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FInterpTo_Constant_DeltaTime_WideningCast; // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget) == 0x000008, "Wrong alignment on UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget");
static_assert(sizeof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget) == 0x0002A8, "Wrong size on UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, EntryPoint) == 0x000000, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_Create_ReturnValue) == 0x000008, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_byte_Variable) == 0x000010, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable) == 0x000018, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable_1) == 0x000028, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_byte_Variable_1) == 0x000038, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable_2) == 0x000040, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable_3) == 0x000050, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_byte_Variable_2) == 0x000060, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable_4) == 0x000068, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_struct_Variable_5) == 0x000078, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_struct_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_byte_Variable_3) == 0x000088, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_int_Variable) == 0x00008C, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_Add_IntInt_ReturnValue) == 0x000090, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Event_IsDesignTime) == 0x000094, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Event_MyGeometry) == 0x000098, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Event_InDeltaTime) == 0x0000D8, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_KillerName) == 0x0000E0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_KillerName' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_VictimName) == 0x0000F8, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_VictimName' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_Icon) == 0x000110, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_Icon' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_KillerNameColor) == 0x000118, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_KillerNameColor' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_VictimNameColor) == 0x00012C, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_VictimNameColor' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_CustomEvent_IconColor) == 0x000140, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_CustomEvent_IconColor' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetChildrenCount_ReturnValue) == 0x000154, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, Temp_int_Variable_1) == 0x000158, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetChildAt_ReturnValue) == 0x000160, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_DynamicCast_AsUI_Kill_Feed_Element) == 0x000168, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_DynamicCast_AsUI_Kill_Feed_Element' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_DynamicCast_bSuccess) == 0x000170, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000171, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_Add_IntInt_ReturnValue_1) == 0x000174, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_AddChildToCanvas_ReturnValue) == 0x000178, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_AddChildToCanvas_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetChildAt_ReturnValue_1) == 0x000180, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetChildAt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetChildrenCount_ReturnValue_1) == 0x000188, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetChildrenCount_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_DynamicCast_AsUI_Kill_Feed_Element_1) == 0x000190, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_DynamicCast_AsUI_Kill_Feed_Element_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_DynamicCast_bSuccess_1) == 0x000198, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000199, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x0001A0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x0001A8, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_GetPosition_ReturnValue) == 0x0001B0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_GetPosition_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_BreakVector2D_X) == 0x0001C0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_BreakVector2D_Y) == 0x0001C8, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_Add_DoubleDouble_ReturnValue) == 0x0001D0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_FInterpTo_Constant_ReturnValue) == 0x0001D8, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_FInterpTo_Constant_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_MakeVector2D_ReturnValue) == 0x0001E0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Select_Default) == 0x0001F0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Select_Default_1) == 0x000200, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_MakeStruct_Anchors) == 0x000210, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Select_Default_2) == 0x000230, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_SlotAsCanvasSlot_ReturnValue_1) == 0x000240, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_SlotAsCanvasSlot_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_MakeStruct_Anchors_1) == 0x000248, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_MakeStruct_Anchors_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_BreakVector2D_X_1) == 0x000268, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_BreakVector2D_Y_1) == 0x000270, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000278, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_MakeVector2D_ReturnValue_1) == 0x000280, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, K2Node_Select_Default_3) == 0x000290, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget, CallFunc_FInterpTo_Constant_DeltaTime_WideningCast) == 0x0002A0, "Member 'UI_KillFeedWidget_C_ExecuteUbergraph_UI_KillFeedWidget::CallFunc_FInterpTo_Constant_DeltaTime_WideningCast' has a wrong offset!");

}

