#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Viewbob

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Viewbob.Viewbob_C
// 0x0000 (0x0230 - 0x0230)
class UViewbob_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Viewbob_C">();
	}
	static class UViewbob_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UViewbob_C>();
	}
};
static_assert(alignof(UViewbob_C) == 0x000010, "Wrong alignment on UViewbob_C");
static_assert(sizeof(UViewbob_C) == 0x000230, "Wrong size on UViewbob_C");

}

